name: Metrics Weekly

on:
  # Allow manual triggering
  workflow_dispatch:

  # Scheduled run every Monday at 12:00 AM CST (06:00 UTC)
  schedule:
    # Runs at 06:00 UTC every Monday (12:00 AM CST)
    - cron: '0 6 * * 1'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment with version 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Create base64 encoded content from service_account.json
    - name: Create file
      run: cat service_account.json | base64

    # Step 4: Create service_account.json file from the secret in environment variables
    - name: Putting data
      env:
        DATA: ${{ secrets.SERVICE_ACCOUNT }}
      run: echo $DATA > service_account.json

    # Step 5: Install Python dependencies from requirements.txt (if it exists)
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 6: Run the Python script with credentials from a secret
    - name: Run Python script
      run: python main.py
      env:
        INSTRUQT_CREDS: ${{ secrets.INSTRUQT_CREDS }}
